[package]
name = 'bayou'
version = '1.0.0'

[addresses]
hello_move = "0x33"
token_sender = "0x333"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
